/**
 * Generate src/system/registry.ts: every card folder (a README.md beside an index.tsx) in the component layers, with a
 * lazy import of its preview. The Atlas reads it; nothing else does.
 *
 *   node scripts/registry.ts           write it
 *   node scripts/registry.ts --check   exit 1 if it is out of date or a card is missing its preview
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
export const LAYERS = [
  { dir: 'src/components/base', layer: 1, section: 'base' },
  { dir: 'src/components/ui', layer: 2, section: 'components' },
  { dir: 'src/components/patterns', layer: 3, section: 'patterns' },
  { dir: 'src/components/charts', layer: 3, section: 'patterns' },
] as const;

export type CardEntry = { id: string; layer: number; section: string; dir: string; hasPreview: boolean };

export function cards(): CardEntry[] {
  const out: CardEntry[] = [];
  for (const l of LAYERS) {
    const abs = path.join(ROOT, l.dir);
    for (const name of fs.readdirSync(abs).sort()) {
      const d = path.join(abs, name);
      if (!fs.statSync(d).isDirectory() || !fs.existsSync(path.join(d, 'README.md'))) continue;
      out.push({ id: name, layer: l.layer, section: l.section, dir: `${l.dir}/${name}`, hasPreview: fs.existsSync(path.join(d, 'preview.tsx')) });
    }
  }
  return out;
}

function build() {
  const list = cards();
  const lines = [
    '/* GENERATED by scripts/registry.ts from the card folders. Do not edit. */',
    "import dynamic from 'next/dynamic';",
    "import type { ComponentType } from 'react';",
    '',
    'export type Card = { id: string; layer: number; section: string; dir: string; Preview: ComponentType | null };',
    '',
    'export const CARDS: Card[] = [',
    ...list.map((c) => `  { id: '${c.id}', layer: ${c.layer}, section: '${c.section}', dir: '${c.dir}', Preview: ${c.hasPreview ? `dynamic(() => import('@/${c.dir.replace(/^src\//, '')}/preview'))` : 'null'} },`),
    '];',
    '',
  ];
  return lines.join('\n');
}

if (import.meta.main) {
  const file = path.join(ROOT, 'src/system/registry.ts');
  const next = build();
  if (process.argv.includes('--check')) {
    const missing = cards().filter((c) => !c.hasPreview).map((c) => c.dir);
    const stale = !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== next;
    if (stale) console.log('src/system/registry.ts is out of date: run node scripts/registry.ts');
    for (const m of missing) console.log(`${m}: no preview.tsx`);
    console.log(stale || missing.length ? '' : `registry: ${cards().length} cards, all with previews`);
    process.exit(stale || missing.length ? 1 : 0);
  }
  fs.writeFileSync(file, next);
  console.log(`src/system/registry.ts: ${cards().length} cards`);
}
